type Usuario @table {
  id: UUID! @default(expr: "uuidV4()")
  nome: String!
  email: String! @unique
  senhaHash: String!
  tipo: String!
  criadoEm: Timestamp! @default(expr: "request.time")
}

type Paciente @table {
  id: UUID! @default(expr: "uuidV4()")
  nome: String!
  responsavelId: UUID!
  responsavel: Usuario!
  nascimento: Date
  peso: Float
  alergias: String
  criadoEm: Timestamp! @default(expr: "request.time")
}

type NutricionistaPaciente @table(key: ["nutricionistaId", "pacienteId"]) {
  nutricionistaId: UUID!
  pacienteId: UUID!
  nutricionista: Usuario!
  paciente: Paciente!
  vinculadoEm: Timestamp! @default(expr: "request.time")
}

type Refeicao @table {
  id: UUID! @default(expr: "uuidV4()")
  pacienteId: UUID!
  paciente: Paciente!
  dataHora: Timestamp! @default(expr: "request.time")
  status: String!
  urlFotoAntes: String!
  urlFotoDepois: String
}

type Alimento @table {
  id: UUID! @default(expr: "uuidV4()")
  label: String! @unique
  categoria: String
}

type DeteccaoAlimento @table {
  id: UUID! @default(expr: "uuidV4()")
  refeicaoId: UUID!
  refeicao: Refeicao!
  alimentoId: UUID!
  alimento: Alimento!
  confidence: Float!
  percentualConsumido: Float!
  aceito: Boolean! @default(value: false)
  cor: String
  textura: String
  criadoEm: Timestamp! @default(expr: "request.time")
}

type Relatorio @table {
  id: UUID! @default(expr: "uuidV4()")
  refeicaoId: UUID!
  refeicao: Refeicao!
  pacienteId: UUID!
  paciente: Paciente!
  dataGeracao: Timestamp! @default(expr: "request.time")
  conteudo: String!
}