// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIJ0o23O0SpokbZlXOHBfHl1tCVCgM2w',
    appId: '1:71863922193:web:cb639546e3180976fc0bb0',
    messagingSenderId: '71863922193',
    projectId: 'pi-v-appetit',
    authDomain: 'pi-v-appetit.firebaseapp.com',
    storageBucket: 'pi-v-appetit.firebasestorage.app',
    measurementId: 'G-841ZX4V3LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEOXuw35V1Y4GcwryQq4HxbRdwDVk_3E',
    appId: '1:71863922193:android:cb3c5ca5cc6a1018fc0bb0',
    messagingSenderId: '71863922193',
    projectId: 'pi-v-appetit',
    storageBucket: 'pi-v-appetit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJDYgccKOsBlAY33FWpI2nXlJLZgTDvVg',
    appId: '1:71863922193:ios:6b2ae0efe35a064afc0bb0',
    messagingSenderId: '71863922193',
    projectId: 'pi-v-appetit',
    storageBucket: 'pi-v-appetit.firebasestorage.app',
    iosBundleId: 'com.example.projectAppetit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJDYgccKOsBlAY33FWpI2nXlJLZgTDvVg',
    appId: '1:71863922193:ios:6b2ae0efe35a064afc0bb0',
    messagingSenderId: '71863922193',
    projectId: 'pi-v-appetit',
    storageBucket: 'pi-v-appetit.firebasestorage.app',
    iosBundleId: 'com.example.projectAppetit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAIJ0o23O0SpokbZlXOHBfHl1tCVCgM2w',
    appId: '1:71863922193:web:3cbfa842ee09bf25fc0bb0',
    messagingSenderId: '71863922193',
    projectId: 'pi-v-appetit',
    authDomain: 'pi-v-appetit.firebaseapp.com',
    storageBucket: 'pi-v-appetit.firebasestorage.app',
    measurementId: 'G-4Y7WB0CJ6Y',
  );
}
