# -*- coding: utf-8 -*-
"""ScriptTreino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6ZzfVSb9jN4fre4X2fCakt2dfvkGe3v
"""

from google.colab import drive
drive.mount('/content/drive')

# 1. Instalar o YOLO
!pip install ultralytics

# 2. Descompactar o dataset
# Ajuste o caminho abaixo se o nome da pasta no Drive for diferente
!unzip -q /content/drive/MyDrive/PI_V/dataset_final_yolo.zip -d /content/

from ultralytics import YOLO

# Carrega o modelo
model = YOLO('yolov8n.pt')

# Treina (ajustamos o caminho do yaml para o Colab)
model.train(data='/content/comida.yaml', epochs=50, imgsz=640, device=0)

from ultralytics import YOLO

# Note que usamos 'train2' pois foi onde o YOLO salvou desta vez
model = YOLO('/content/runs/detect/train4/weights/best.pt')

# Roda a validação detalhada
metrics = model.val()

print("\n" + "="*30)
print(f"RESUMO DAS MÉTRICAS:")
print(f"Precisão (Precision): {metrics.results_dict['metrics/precision(B)']:.4f}")
print(f"Revocação (Recall): {metrics.results_dict['metrics/recall(B)']:.4f}")
print(f"mAP50: {metrics.results_dict['metrics/mAP50(B)']:.4f}")
print("="*30)

from ultralytics import YOLO
from google.colab import files
import cv2
from google.colab.patches import cv2_imshow

# 1. Carregar o modelo que você acabou de treinar
model = YOLO('/content/runs/detect/train4/weights/best.pt')

# 2. Upload da imagem
print("Selecione uma foto de comida para testar:")
uploaded = files.upload()

for fn in uploaded.keys():
    # 3. Rodar a predição
    results = model.predict(source=fn)

    # 4. Mostrar o resultado visual
    res_plotted = results[0].plot()
    cv2_imshow(res_plotted)