# -*- coding: utf-8 -*-
"""ScriptTreinoVERSAO2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNMilJQmSRMX2kv5I6iLnc8CcvwggCRp
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

# 2. Descompactar o dataset
# Removemos a pasta antiga antes para garantir que não haja arquivos corrompidos
!rm -rf /content/test
!unzip -q /content/drive/MyDrive/PI_V/test.zip -d /content/

from ultralytics import YOLO

# Carrega o modelo 'Small' (yolov8s) - ele é muito melhor para identificar arroz e milho que o 'Nano'
model = YOLO('yolov8s.pt')

# Treina com 100 épocas para dar tempo do modelo aprender texturas claras (arroz/milho)
model.train(data='/content/comida.yaml', epochs=100, imgsz=640, device=0, name='treino_melhorado')

from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow

# Agora apontamos para a pasta 'treino_melhorado' que criamos acima
model = YOLO('/content/runs/detect/treino_melhorado4/weights/best.pt')

# Roda a validação detalhada
metrics = model.val()

print("\n" + "="*30)
print(f"RESUMO DAS MÉTRICAS:")
print(f"Precisão (Precision): {metrics.results_dict['metrics/precision(B)']:.4f}")
print(f"Revocação (Recall): {metrics.results_dict['metrics/recall(B)']:.4f}")
print(f"mAP50: {metrics.results_dict['metrics/mAP50(B)']:.4f}")
print("="*30)

# Bloco de Teste Prático (IMPORTANTE: Baixamos a confiança para 0.15)
print("Selecione a foto para testar (Arroz, Carne e Milho):")
uploaded = files.upload()
for fn in uploaded.keys():
    # conf=0.15 força o modelo a mostrar o que ele tem "dúvida", revelando o arroz e o milho
    results = model.predict(source=fn)
    res_plotted = results[0].plot()
    cv2_imshow(res_plotted)



from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow

# Agora apontamos para a pasta 'treino_melhorado' que criamos acima
model = YOLO('/content/runs/detect/treino_melhorado4/weights/best.pt')

# Roda a validação detalhada
metrics = model.val()

print("\n" + "="*30)
print(f"RESUMO DAS MÉTRICAS:")
print(f"Precisão (Precision): {metrics.results_dict['metrics/precision(B)']:.4f}")
print(f"Revocação (Recall): {metrics.results_dict['metrics/recall(B)']:.4f}")
print(f"mAP50: {metrics.results_dict['metrics/mAP50(B)']:.4f}")
print("="*30)

# Bloco de Teste Prático (IMPORTANTE: Baixamos a confiança para 0.15)
print("Selecione a foto para testar (Arroz, Carne e Milho):")
uploaded = files.upload()
for fn in uploaded.keys():
    # conf=0.15 força o modelo a mostrar o que ele tem "dúvida", revelando o arroz e o milho
    results = model.predict(source=fn)
    res_plotted = results[0].plot()
    cv2_imshow(res_plotted)

from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow

# Agora apontamos para a pasta 'treino_melhorado' que criamos acima
model = YOLO('/content/runs/detect/treino_melhorado4/weights/best.pt')

# Roda a validação detalhada
metrics = model.val()

print("\n" + "="*30)
print(f"RESUMO DAS MÉTRICAS:")
print(f"Precisão (Precision): {metrics.results_dict['metrics/precision(B)']:.4f}")
print(f"Revocação (Recall): {metrics.results_dict['metrics/recall(B)']:.4f}")
print(f"mAP50: {metrics.results_dict['metrics/mAP50(B)']:.4f}")
print("="*30)

# Bloco de Teste Prático (IMPORTANTE: Baixamos a confiança para 0.15)
print("Selecione a foto para testar (Arroz, Carne e Milho):")
uploaded = files.upload()
for fn in uploaded.keys():
    # conf=0.15 força o modelo a mostrar o que ele tem "dúvida", revelando o arroz e o milho
    results = model.predict(source=fn)
    res_plotted = results[0].plot()
    cv2_imshow(res_plotted)

from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow

# Agora apontamos para a pasta 'treino_melhorado' que criamos acima
model = YOLO('/content/runs/detect/treino_melhorado4/weights/best.pt')

# Roda a validação detalhada
metrics = model.val()

print("\n" + "="*30)
print(f"RESUMO DAS MÉTRICAS:")
print(f"Precisão (Precision): {metrics.results_dict['metrics/precision(B)']:.4f}")
print(f"Revocação (Recall): {metrics.results_dict['metrics/recall(B)']:.4f}")
print(f"mAP50: {metrics.results_dict['metrics/mAP50(B)']:.4f}")
print("="*30)

# Bloco de Teste Prático (IMPORTANTE: Baixamos a confiança para 0.15)
print("Selecione a foto para testar (Arroz, Carne e Milho):")
uploaded = files.upload()
for fn in uploaded.keys():
    # conf=0.15 força o modelo a mostrar o que ele tem "dúvida", revelando o arroz e o milho
    results = model.predict(source=fn, conf=0.3)
    res_plotted = results[0].plot()
    cv2_imshow(res_plotted)