extend type DeteccaoAlimento {
  """
  ✨ Implicit foreign key field based on `DeteccaoAlimento`.`alimento`. It must match the value of `Alimento`.`id`. See `@ref` for how to customize it.
  """
  alimentoId: UUID! @fdc_generated(from: "DeteccaoAlimento.alimento", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DeteccaoAlimento`.`refeicao`. It must match the value of `Refeicao`.`id`. See `@ref` for how to customize it.
  """
  refeicaoId: UUID! @fdc_generated(from: "DeteccaoAlimento.refeicao", purpose: IMPLICIT_REF_FIELD)
}
extend type NutricionistaPaciente {
  """
  ✨ Implicit foreign key field based on `NutricionistaPaciente`.`nutricionista`. It must match the value of `Usuario`.`id`. See `@ref` for how to customize it.
  """
  nutricionistaId: UUID! @fdc_generated(from: "NutricionistaPaciente.nutricionista", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `NutricionistaPaciente`.`paciente`. It must match the value of `Paciente`.`id`. See `@ref` for how to customize it.
  """
  pacienteId: UUID! @fdc_generated(from: "NutricionistaPaciente.paciente", purpose: IMPLICIT_REF_FIELD)
}
extend type Paciente {
  """
  ✨ Implicit foreign key field based on `Paciente`.`responsavel`. It must match the value of `Usuario`.`id`. See `@ref` for how to customize it.
  """
  responsavelId: UUID! @fdc_generated(from: "Paciente.responsavel", purpose: IMPLICIT_REF_FIELD)
}
extend type Refeicao {
  """
  ✨ Implicit foreign key field based on `Refeicao`.`paciente`. It must match the value of `Paciente`.`id`. See `@ref` for how to customize it.
  """
  pacienteId: UUID! @fdc_generated(from: "Refeicao.paciente", purpose: IMPLICIT_REF_FIELD)
}
