extend type Mutation {
  """
  ✨ Insert a single `Paciente` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  paciente_insert(
    """
    Data object to insert into the table.
    """
    data: Paciente_Data!
  ): Paciente_KeyOutput! @fdc_generated(from: "Paciente", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Refeicao` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  refeicao_insert(
    """
    Data object to insert into the table.
    """
    data: Refeicao_Data!
  ): Refeicao_KeyOutput! @fdc_generated(from: "Refeicao", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Usuario` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  usuario_insert(
    """
    Data object to insert into the table.
    """
    data: Usuario_Data!
  ): Usuario_KeyOutput! @fdc_generated(from: "Usuario", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Paciente` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  paciente_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Paciente_Data!]!
  ): [Paciente_KeyOutput!]! @fdc_generated(from: "Paciente", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Refeicao` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  refeicao_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Refeicao_Data!]!
  ): [Refeicao_KeyOutput!]! @fdc_generated(from: "Refeicao", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Usuario` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  usuario_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Usuario_Data!]!
  ): [Usuario_KeyOutput!]! @fdc_generated(from: "Usuario", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Paciente` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Paciente`.
  """
  paciente_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Paciente_Data!
  ): Paciente_KeyOutput! @fdc_generated(from: "Paciente", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Refeicao` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Refeicao`.
  """
  refeicao_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Refeicao_Data!
  ): Refeicao_KeyOutput! @fdc_generated(from: "Refeicao", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Usuario` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Usuario`.
  """
  usuario_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Usuario_Data!
  ): Usuario_KeyOutput! @fdc_generated(from: "Usuario", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Paciente` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Paciente`.
  """
  paciente_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Paciente_Data!]!
  ): [Paciente_KeyOutput!]! @fdc_generated(from: "Paciente", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Refeicao` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Refeicao`.
  """
  refeicao_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Refeicao_Data!]!
  ): [Refeicao_KeyOutput!]! @fdc_generated(from: "Refeicao", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Usuario` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Usuario`.
  """
  usuario_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Usuario_Data!]!
  ): [Usuario_KeyOutput!]! @fdc_generated(from: "Usuario", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Paciente` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Paciente` or `null` if not found.
  """
  paciente_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Paciente_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Paciente_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Paciente_Data!
  ): Paciente_KeyOutput @fdc_generated(from: "Paciente", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Refeicao` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Refeicao` or `null` if not found.
  """
  refeicao_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Refeicao_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Refeicao_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Refeicao_Data!
  ): Refeicao_KeyOutput @fdc_generated(from: "Refeicao", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Usuario` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Usuario` or `null` if not found.
  """
  usuario_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Usuario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Usuario_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Usuario_Data!
  ): Usuario_KeyOutput @fdc_generated(from: "Usuario", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Paciente` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  paciente_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Paciente_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Paciente_Data!
  ): Int! @fdc_generated(from: "Paciente", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Refeicao` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  refeicao_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Refeicao_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Refeicao_Data!
  ): Int! @fdc_generated(from: "Refeicao", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Usuario` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  usuario_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Usuario_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Usuario_Data!
  ): Int! @fdc_generated(from: "Usuario", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Paciente` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  paciente_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Paciente_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Paciente_FirstRow
  ): Paciente_KeyOutput @fdc_generated(from: "Paciente", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Refeicao` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  refeicao_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Refeicao_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Refeicao_FirstRow
  ): Refeicao_KeyOutput @fdc_generated(from: "Refeicao", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Usuario` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  usuario_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Usuario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Usuario_FirstRow
  ): Usuario_KeyOutput @fdc_generated(from: "Usuario", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Paciente` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  paciente_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Paciente_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Paciente", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Refeicao` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  refeicao_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Refeicao_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Usuario` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  usuario_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Usuario_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Usuario", purpose: DELETE_MULTIPLE)
}
