extend type Query {
  """
  ✨ Look up a single `Paciente` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  paciente(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Paciente_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Paciente_FirstRow
  ): Paciente @fdc_generated(from: "Paciente", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Refeicao` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  refeicao(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Refeicao_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Refeicao_FirstRow
  ): Refeicao @fdc_generated(from: "Refeicao", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Usuario` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  usuario(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Usuario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Usuario_FirstRow
  ): Usuario @fdc_generated(from: "Usuario", purpose: QUERY_SINGLE)
  """
  ✨ List `Paciente` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  pacientes(
    """
    Filter condition to narrow down the query results.
    """
    where: Paciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Paciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Paciente_Having
  ): [Paciente!]! @fdc_generated(from: "Paciente", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Refeicao` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  refeicaos(
    """
    Filter condition to narrow down the query results.
    """
    where: Refeicao_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Refeicao_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Refeicao_Having
  ): [Refeicao!]! @fdc_generated(from: "Refeicao", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Usuario` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  usuarios(
    """
    Filter condition to narrow down the query results.
    """
    where: Usuario_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Usuario_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Usuario_Having
  ): [Usuario!]! @fdc_generated(from: "Usuario", purpose: QUERY_MULTIPLE)
}
