extend type Alimento {
  """
  ✨ List `DeteccaoAlimento` objects in a one-to-many relationship (where `DeteccaoAlimento`.`alimento` is this object).
  """
  deteccaoAlimentos_on_alimento(
    """
    Filter condition to narrow down the query results.
    """
    where: DeteccaoAlimento_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DeteccaoAlimento_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DeteccaoAlimento_Having
  ): [DeteccaoAlimento!]! @fdc_generated(from: "DeteccaoAlimento.alimento", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Alimento", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Alimento` table.
  """
  _count: Int! @fdc_generated(from: "Alimento.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Alimento` table where the `categoria` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoria_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Alimento.categoria", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Alimento` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Alimento.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Alimento` table where the `label` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  label_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Alimento.label", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Alimento.id", purpose: ENTITY_ID)
}
extend type DeteccaoAlimento {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "DeteccaoAlimento", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table.
  """
  _count: Int! @fdc_generated(from: "DeteccaoAlimento.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `aceito` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  aceito_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.aceito", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `alimentoId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  alimentoId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.alimentoId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `cor` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cor_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.cor", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `percentualConsumido` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  percentualConsumido_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.percentualConsumido", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `refeicaoId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  refeicaoId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.refeicaoId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DeteccaoAlimento` table where the `textura` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  textura_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DeteccaoAlimento.textura", purpose: QUERY_COUNT)
  """
  ✨ Sum the `percentualConsumido` field in the `DeteccaoAlimento` table.
  """
  percentualConsumido_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DeteccaoAlimento.percentualConsumido", purpose: QUERY_SUM)
  """
  ✨ Average the `percentualConsumido` field in the `DeteccaoAlimento` table.
  """
  percentualConsumido_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "DeteccaoAlimento.percentualConsumido", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `percentualConsumido` field in the `DeteccaoAlimento` table.
  """
  percentualConsumido_min: Float @fdc_generated(from: "DeteccaoAlimento.percentualConsumido", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `percentualConsumido` field in the `DeteccaoAlimento` table.
  """
  percentualConsumido_max: Float @fdc_generated(from: "DeteccaoAlimento.percentualConsumido", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "DeteccaoAlimento.id", purpose: ENTITY_ID)
}
extend type NutricionistaPaciente {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "NutricionistaPaciente", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `NutricionistaPaciente` table.
  """
  _count: Int! @fdc_generated(from: "NutricionistaPaciente.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NutricionistaPaciente` table where the `nutricionistaId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nutricionistaId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NutricionistaPaciente.nutricionistaId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NutricionistaPaciente` table where the `pacienteId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pacienteId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NutricionistaPaciente.pacienteId", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "NutricionistaPaciente.nutricionistaId,pacienteId", purpose: ENTITY_ID)
}
extend type Paciente {
  """
  ✨ List `NutricionistaPaciente` objects in a one-to-many relationship (where `NutricionistaPaciente`.`paciente` is this object).
  """
  nutricionistaPacientes_on_paciente(
    """
    Filter condition to narrow down the query results.
    """
    where: NutricionistaPaciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NutricionistaPaciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NutricionistaPaciente_Having
  ): [NutricionistaPaciente!]! @fdc_generated(from: "NutricionistaPaciente.paciente", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Refeicao` objects in a one-to-many relationship (where `Refeicao`.`paciente` is this object).
  """
  refeicaos_on_paciente(
    """
    Filter condition to narrow down the query results.
    """
    where: Refeicao_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Refeicao_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Refeicao_Having
  ): [Refeicao!]! @fdc_generated(from: "Refeicao.paciente", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Usuario` objects using `NutricionistaPaciente` as the join table (a `NutricionistaPaciente` object exists where its `paciente` is this and its `nutricionista` is that).
  """
  usuarios_via_NutricionistaPaciente(
    """
    Filter condition to narrow down the query results.
    """
    where: NutricionistaPaciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NutricionistaPaciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NutricionistaPaciente_Having
  ): [Usuario!]! @fdc_generated(from: "NutricionistaPaciente", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Paciente", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Paciente` table.
  """
  _count: Int! @fdc_generated(from: "Paciente.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Paciente` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Paciente.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Paciente` table where the `nascimento` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nascimento_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Paciente.nascimento", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Paciente` table where the `nome` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nome_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Paciente.nome", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Paciente` table where the `responsavelId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  responsavelId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Paciente.responsavelId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `nascimento` field in the `Paciente` table.
  """
  nascimento_min: Date @fdc_generated(from: "Paciente.nascimento", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `nascimento` field in the `Paciente` table.
  """
  nascimento_max: Date @fdc_generated(from: "Paciente.nascimento", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Paciente.id", purpose: ENTITY_ID)
}
extend type Refeicao {
  """
  ✨ List `DeteccaoAlimento` objects in a one-to-many relationship (where `DeteccaoAlimento`.`refeicao` is this object).
  """
  deteccaoAlimentos_on_refeicao(
    """
    Filter condition to narrow down the query results.
    """
    where: DeteccaoAlimento_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DeteccaoAlimento_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DeteccaoAlimento_Having
  ): [DeteccaoAlimento!]! @fdc_generated(from: "DeteccaoAlimento.refeicao", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Refeicao", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Refeicao` table.
  """
  _count: Int! @fdc_generated(from: "Refeicao.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `dataHora` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dataHora_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.dataHora", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `pacienteId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  pacienteId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.pacienteId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `urlFotoAntes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  urlFotoAntes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.urlFotoAntes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Refeicao` table where the `urlFotoDepois` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  urlFotoDepois_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Refeicao.urlFotoDepois", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `dataHora` field in the `Refeicao` table.
  """
  dataHora_min: Timestamp @fdc_generated(from: "Refeicao.dataHora", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `dataHora` field in the `Refeicao` table.
  """
  dataHora_max: Timestamp @fdc_generated(from: "Refeicao.dataHora", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Refeicao.id", purpose: ENTITY_ID)
}
extend type Usuario {
  """
  ✨ List `NutricionistaPaciente` objects in a one-to-many relationship (where `NutricionistaPaciente`.`nutricionista` is this object).
  """
  nutricionistaPacientes_on_nutricionista(
    """
    Filter condition to narrow down the query results.
    """
    where: NutricionistaPaciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NutricionistaPaciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NutricionistaPaciente_Having
  ): [NutricionistaPaciente!]! @fdc_generated(from: "NutricionistaPaciente.nutricionista", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Paciente` objects in a one-to-many relationship (where `Paciente`.`responsavel` is this object).
  """
  pacientes_on_responsavel(
    """
    Filter condition to narrow down the query results.
    """
    where: Paciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Paciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Paciente_Having
  ): [Paciente!]! @fdc_generated(from: "Paciente.responsavel", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Paciente` objects using `NutricionistaPaciente` as the join table (a `NutricionistaPaciente` object exists where its `nutricionista` is this and its `paciente` is that).
  """
  pacientes_via_NutricionistaPaciente(
    """
    Filter condition to narrow down the query results.
    """
    where: NutricionistaPaciente_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NutricionistaPaciente_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NutricionistaPaciente_Having
  ): [Paciente!]! @fdc_generated(from: "NutricionistaPaciente", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Usuario", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Usuario` table.
  """
  _count: Int! @fdc_generated(from: "Usuario.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `criadoEm` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  criadoEm_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.criadoEm", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `nome` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nome_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.nome", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `senhaHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  senhaHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.senhaHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Usuario` table where the `tipo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tipo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Usuario.tipo", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `criadoEm` field in the `Usuario` table.
  """
  criadoEm_min: Timestamp @fdc_generated(from: "Usuario.criadoEm", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `criadoEm` field in the `Usuario` table.
  """
  criadoEm_max: Timestamp @fdc_generated(from: "Usuario.criadoEm", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Usuario.id", purpose: ENTITY_ID)
}
